# Rustfmt configuration for AeroSocket
# Ensures consistent code formatting across the project

edition = "2021"
hard_tabs = false
tab_spaces = 4
max_width = 100
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
edition_2021 = true
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true
license_template_path = ".license-template"
format_strings = false
format_macro_matchers = true
format_macro_bodies = true
hex_literal = "Preserve"
overflow_delimited_expr = false
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
spaces_around_ranges = false
binop_separator = "Front"
remove_parentheses = true
combine_control_expr = true
control_brace_style = "AlwaysSameLine"
trailing_comma = "Vertical"
match_block_trailing_comma = false
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
wrap_comments = false
comment_width = 80
wrap_match_arms = true
match_arm_blocks = true
force_multiline_blocks = false
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
indent_style = "Block"
space_before_colon = false
space_after_colon = true
spaces_around_colon = false
eol_newline = true
merge_imports = true
